---
# Set to true to skip module compilation (for roles requiring proprietary SDKs)
skip_compilation: false

verification:
  files_must_exist:
    # Standard IOC boot files (created by deploy_ioc)
    - st.cmd
    - pixi.toml
  file_must_contain:
    st.cmd:
      # Make sure EPICS networking env vars get set
      - "export EPICS_CA_AUTO_ADDR_LIST"
      - "export EPICS_CAS_AUTO_BEACON_ADDR_LIST"
      - "export EPICS_CA_ADDR_LIST"
      - "export EPICS_CAS_BEACON_ADDR_LIST"

      # Make sure we run the correct exec
      - "pixi run remote-svc-ctrl"
      - "XF:31ID1-CT{SVC-XSPD:1}"
      - "xspd.service"
      - "--host xspadmin@xf31id1-lambda1"
      - "--log-lines 30"

  permissions:
    st.cmd: "0775"
