---
# Set to true to skip module compilation (for roles requiring proprietary SDKs)
skip_compilation: false

verification:
  files_must_exist:
    # Standard IOC boot files (created by deploy_ioc)
    - st.cmd
    - pixi.toml
  file_must_contain:
    st.cmd:
      # Make sure EPICS networking env vars get set
      - "export EPICS_CA_AUTO_ADDR_LIST"
      - "export EPICS_CAS_AUTO_BEACON_ADDR_LIST"
      - "export EPICS_CA_ADDR_LIST"
      - "export EPICS_CAS_BEACON_ADDR_LIST"

      # Make sure environment variables are exported
      - "export PREFIX=XF:31ID1-CT{SVC-XSPD:1}"
      - "export SERVICE=xspd.service"
      - "export USERNAME=xspadmin"
      - "export HOST=xf31id1-lambda1"

      # Make sure we run the correct exec
      - "pixi run ioc"

  permissions:
    st.cmd: "0775"
