---

- name: Install files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ deploy_ioc_ioc_directory }}/"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
  with_fileglob: "files/*"

- name: Install dependencies
  ansible.builtin.command:
    cmd: "{{ ioc.pixi_executable_path | default(deploy_ioc_pixi_executable_path) }} install"
    chdir: "{{ deploy_ioc_ioc_directory }}"
  changed_when: true

- name: Install startup script
  ansible.builtin.template:
    src: "templates/st.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/st.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0775"
